# Generated by Django 5.2.11 on 2026-02-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_alter_reservation_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
