# Generated by Django 5.2.11 on 2026-02-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_reservation_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='requested', max_length=20),
        ),
    ]
