# Generated by Django 5.2.11 on 2026-03-02 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_remove_reservation_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room', 'check_in', 'check_out'], name='hotel_app_r_room_id_9dfaf6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='hotel_app_r_status_851d18_idx'),
        ),
    ]
